# Generated by Django 3.2.12 on 2022-02-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=15, verbose_name='IP адрес')),
                ('text', models.TextField(verbose_name='Текст лога')),
                ('log_time', models.DateTimeField(db_index=True, verbose_name='Время лога')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
